const express = require("express");
const router = express.Router();
const {User} = require("../db/index"); 
const { validateUserSignup, validateUserSignin, validateUserVerify, tokenValidation } = require("../middlewares/UserMiddlewares");
const jwt = require("jsonwebtoken");
const {sendOtpEmail} = require("../utils/OtpMailer")
require('dotenv').config();
const bcrypt = require("bcrypt");

router.post("/signup", validateUserSignup, async (req, res) => {
    try {
        // Destructure the validated data from the request body
        const { name, email, password } = req.body;

        // Hash the password before storing it
        // You can use bcrypt or another library to hash the password
        const bcrypt = require("bcrypt");
        const saltRounds = 10;
        const password_hash = await bcrypt.hash(password, saltRounds);

        // Create a new user instance
        const newUser = new User({
            name:name.trim(),
            email:email.trim(),
            password_hash,
            // Registration OTP will be generated by the schema's default value
        });

        // Save the user to the database
        await newUser.save();

        // Send a success response
        return res.status(201).json({
            message: "User registered successfully.",
            email: newUser.email,
            user_id:newUser._id
        });
    } catch (error) {
        console.error("Error creating user:", error);
        return res.status(500).json({
            errors: ["Internal server error."],
        });
    }
});


router.post("/signin", validateUserSignin,(req,res)=>{
    // all checks done create a jwt token using user's email and send it in response 
    const { email } = req.body;
    const token = jwt.sign({ email,user_id:req.user_id }, process.env.JWT_SECRET, {
        expiresIn: "12h",
    });
    return res.status(200).json({
        message: "User signed in successfully.",
        token,
        name:req.user.name,
        email:req.user.email,
        joined_at:req.user.created_at,
        user_id:req.user._id
    });
})

router.put("/edit-name",tokenValidation,async(req,res)=>{
    //zod input validation for name to be present in req body
    //extract name only from req body
    const { name } = req.body;
    if(name.length<4){
        return res.status(400).json({
            errors: ["Name should be atleast 4 characters."],
        });
    }
    try {
        //get user from req body
        const user=req.user;
        //update user name
        user.name=name;
        //save updated user
        await user.save();
        //send success response
        return res.status(200).json({
            message: "User updated successfully.",
        });
    } catch (error) {
        console.error("Error updating user:", error);
        return res.status(500).json({
            errors: ["Internal server error."],
        });
    }

})

//post request to send resetotp to users mail id 
router.post("/reset",async (req,res)=>{
    //extract email from req body
    const {email}=req.body;
    if(!email){
        return res.status(400).json({
            errors: ["Email is required."],
        });
    }
    //find user with that email
    const user=await User.findOne({email});
    //if no user found send error
    if(!user){
        return res.status(400).json({
            errors: ["No user with this email exists."],
        });
    }
    //if user found check if his state is not blocked
    if(user.state==="blocked"){
        return res.status(400).json({
            errors: ["User is blocked."],
        });
    }
    //if user state is verified send otp to user email
    //send otp to user email
    await sendOtpEmail(user.email,user.reset_otp,"Your One Time Password(OTP) for resetting your password is: ");
    return res.status(200).json({
        message: "OTP sent to user's email.",
    });
})

router.put("/reset",async (req,res)=>{
    //extract email and otp from req body
    const {email,resetOtp,password}=req.body;
    //find user with that email
    const userOne=await User.findOne({
        email
    })
    //if no user found send error
    if(!userOne){
        return res.status(400).json({
            errors: ["No user with this email exists."],
        });
    }
    //if user found check if his state is not blocked
    if(userOne.state==="blocked"){
        return res.status(400).json({
            errors: ["User is blocked."],
        });
    }
    //if otp is correct update user password
    if(userOne.reset_otp===resetOtp){
        //if both password same send 403
        if(await bcrypt.compare(password, userOne.password_hash)){
            userOne.reset_otp=Math.floor(100000 + Math.random() * 900000).toString();
            await userOne.save();
            return res.status(403).json({
                errors: ["New password cannot be same as old password."],
            });
        }
        userOne.password_hash = await bcrypt.hash(password, 10);
        //generate a new otp of 6 digit  number and make it string and update that otp in db
        userOne.reset_otp=Math.floor(100000 + Math.random() * 900000).toString();
        await userOne.save();
        return res.status(200).json({
            message: "Password reset successfully.",
        });
    }
    return res.status(400).json({
        errors: ["Enter a valid OTP."],
    });
})

router.post("/verify", async (req, res) => {
    console.log("Received a POST request to /verify");
    const { email } = req.body;

    // Debug email presence
    if (!email) {
        console.log("No email provided");
        return res.status(400).json({ errors: ["Email is required."] });
    }

    try {
        const user = await User.findOne({ email });
        if (!user) {
            console.log("No user found with email:", email);
            return res.status(401).json({ errors: ["No user with this email exists."] });
        }

        if (user.state === "verified") {
            console.log("User is already verified");
            return res.status(402).json({ errors: ["User is already verified."] });
        }

        console.log("Sending OTP email to:", user.email);
        await sendOtpEmail(user.email, user.registration_otp, "Your OTP is:");
        return res.status(200).json({ message: "OTP sent to user's email." });
    } catch (error) {
        console.error("Error in /verify route:", error.message);
        res.status(500).json({ errors: ["Internal server error."] });
    }
});

router.put("/verify",validateUserVerify, async (req,res)=>{
    //extract email and otp from req body
    const {email,registerOtp}=req.body;
    //find user with that email
    const userOne=await User.findOne({email});
    //if no user found send error
    if(!userOne){
        return res.status(400).json({
            errors: ["No user with this email exists."],
        });
    }
    //if user state is verified send message already verified
    if(userOne.state==="verified"){
        return res.status(401).json({
            errors: ["User is already verified."],
        });
    }
    //if otp is correct update user state to verified
    if(userOne.registration_otp===registerOtp){
        userOne.state="verified";
        //generate a new otp of 6 digit  number and make it string and update that otp in db
        userOne.registration_otp=Math.floor(100000 + Math.random() * 900000).toString();
        await userOne.save();
        //generate new jwt token
        const token = jwt.sign({ email, user_id:userOne.id }, process.env.JWT_SECRET, {
            expiresIn: "12h",
        });
        return res.status(200).json({
            message: "User verified successfully.",
            token,
            name:userOne.name,
            joined_at:userOne.created,
            user_id:userOne._id
        });
    }else{
        return res.status(402).json({
            errors: ["Enter a valid OTP."],
        });
    }
})

router.get("/profile", tokenValidation, async (req,res)=>{
    try {
        const id=req.user_id;
        const RequestedUser=await User.findOne({id})
        if(!RequestedUser){
            return res.status(400).json({
                errors: ["No user with this id exists."],
            });
        }
        return res.status(200).json({
            user_id:RequestedUser.id,
            name:RequestedUser.name,
            email:RequestedUser.email,
            // state:RequestedUser.state,
            // created_at:RequestedUser.created_at,
            // last_login:RequestedUser.last_login
        });   
    } catch (error) {
        console.error("Error getting user:", error);
        return res.status(500).json({
            errors: ["Internal server error."],
        });
    }

})

router.post("/verifyToken",tokenValidation,async (req,res)=>{
    return res.status(200).json({
        message: "Token is valid",
    })
})

router.get("/test",(req,res)=>{
    return res.status(200).json({
        message: "Test route working",
        });
})

module.exports = router;